### ISSUE TITLE
Error when deploying to Netlify

### ISSUE THREAD

**Issue by AmyXS** [ixartz/Next-JS-Landing-Page-Starter-Template#5]
Hi There,

I tried to deploy this template to netlify (clicking on the Deploy to Netlify button in the README), but got this error during the deployment.

Could you please give some insights on how to resolve this?

Plugin "@netlify/plugin-nextjs" failed

Error: The directory "out" does not contain a Next.js production build. Perhaps the build command was not run, or you specified the wrong publish directory.
Your publish directory is set to "out", but in most cases it should be ".next".
If you are using "next export" then you should set the environment variable NETLIFY_NEXT_PLUGIN_SKIP to "true".

In "onBuild" event in "@netlify/plugin-nextjs" from Netlify app at checkNextSiteHasBuilt (/.netlify/plugins/node_modules/@netlify/plugin-nextjs/lib/helpers/verification.js:68:16) at onBuild (/.netlify/plugins/node_modules/@netlify/plugin-nextjs/lib/index.js:37:50)

Logs:
`9:32:37 PM: ────────────────────────────────────────────────────────────────
9:32:37 PM:   Plugin "@netlify/plugin-nextjs" failed                        
9:32:37 PM: ────────────────────────────────────────────────────────────────
9:32:37 PM: ​
9:32:37 PM:   Error message
9:32:37 PM:   Error: The directory "out" does not contain a Next.js production build. Perhaps the build command was not run, or you specified the wrong publish directory.
9:32:37 PM:   Your publish directory is set to "out", but in most cases it should be ".next".
9:32:37 PM:   If you are using "next export" then you should set the environment variable NETLIFY_NEXT_PLUGIN_SKIP to "true".
9:32:37 PM: ​
9:32:37 PM:   Plugin details
9:32:37 PM:   Package:        @netlify/plugin-nextjs
9:32:37 PM:   Version:        4.2.4
9:32:37 PM:   Repository:     git+https://github.com/netlify/netlify-plugin-nextjs.git
9:32:37 PM:   npm link:       https://www.npmjs.com/package/@netlify/plugin-nextjs
9:32:37 PM:   Report issues:  https://github.com/netlify/netlify-plugin-nextjs/issues
9:32:37 PM: ​
9:32:37 PM:   Error location
9:32:37 PM:   In "onBuild" event in "@netlify/plugin-nextjs" from Netlify app
9:32:37 PM:       at checkNextSiteHasBuilt (/.netlify/plugins/node_modules/@netlify/plugin-nextjs/lib/helpers/verification.js:68:16)
9:32:37 PM:       at onBuild (/.netlify/plugins/node_modules/@netlify/plugin-nextjs/lib/index.js:37:50)
9:32:37 PM: ​
9:32:37 PM:   Resolved config
9:32:37 PM:   build:
9:32:37 PM:     command: npm run build-prod
9:32:37 PM:     commandOrigin: config
9:32:37 PM:     environment:
9:32:37 PM:       - NEXT_PRIVATE_TARGET
9:32:37 PM:     publish: /opt/build/repo/out
9:32:37 PM:     publishOrigin: config
9:32:37 PM:   plugins:
9:32:37 PM:     - inputs: {}
9:32:37 PM:       origin: ui
9:32:37 PM:       package: '@netlify/plugin-nextjs'`

**Comment by ixartz** [comment]
Hi @AmyXS, thank you for reporting the issue and it's solved.

Let me know if the problem persists.

If you need the detailed, here is the explanation: https://github.com/ixartz/Next-js-Blog-Boilerplate/issues/8
